{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e95e11d2-69fb-4505-aa65-9a8e07a5b3ad",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "",
   "name": ""
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
